// 可選的歌手。clues 對應 js/clues/ 裡手寫的題庫；沒有題庫的歌手，線索模式改用 iTunes 資料自動出題。
// 沒寫到的欄位（tagline、ranks、colors、icon、countries）會用所屬地區的預設值。

window.REGIONS = [
  { id: "tw", name: "台灣", icon: "🎤", countries: ["tw", "us"], colors: { accent: "#4fd1c5", accent2: "#9be8a8", onAccent: "#04201e" } },
  { id: "twh", name: "台語", icon: "🏮", countries: ["tw", "us"], colors: { accent: "#ff9f43", accent2: "#ffd36b", onAccent: "#1f1102" } },
  { id: "cn", name: "中國", icon: "🐉", countries: ["tw", "cn", "us"], colors: { accent: "#ff5a4f", accent2: "#ffc15e", onAccent: "#260402" } },
  { id: "jp", name: "日本", icon: "🌸", countries: ["tw", "jp", "us"], colors: { accent: "#ff6b8b", accent2: "#ffb7c5", onAccent: "#2a0610" } },
  { id: "kr", name: "韓國", icon: "💜", countries: ["tw", "kr", "us"], colors: { accent: "#9b8cff", accent2: "#5fe1ff", onAccent: "#0d0a2a" } },
  { id: "west", name: "歐美", icon: "🎸", countries: ["tw", "us"], colors: { accent: "#7c8cff", accent2: "#c77dff", onAccent: "#0b0b2a" } },
  { id: "latin", name: "拉丁", icon: "🌶️", countries: ["tw", "us", "mx"], colors: { accent: "#ffc23d", accent2: "#ff5e5b", onAccent: "#241500" } },
  { id: "in", name: "印度", icon: "🪷", countries: ["in", "us"], colors: { accent: "#ff9933", accent2: "#2ec4b6", onAccent: "#1f1000" } },
  { id: "th", name: "泰國", icon: "🐘", countries: ["th", "us"], colors: { accent: "#e0b83a", accent2: "#5ab0ff", onAccent: "#1a1404" } },
];

window.ARTISTS = [
  // ---------- 台灣 ----------
  { region: "tw", id: "jay", name: "周杰倫", terms: ["周杰倫", "Jay Chou"], match: /周杰倫|周杰伦|jay chou/i },
  { region: "tw", id: "mayday", name: "五月天", terms: ["五月天", "Mayday"], match: /五月天|^mayday\b(?! parade)/i },
  { region: "tw", id: "jolin", name: "蔡依林", terms: ["蔡依林", "Jolin Tsai"], match: /蔡依林|jolin tsai/i },
  { region: "tw", id: "amei", name: "張惠妹", terms: ["張惠妹", "A-Mei"], match: /張惠妹|张惠妹|a-?mei|阿密特/i },
  { region: "tw", id: "hebe", name: "田馥甄", terms: ["田馥甄", "Hebe Tien"], match: /田馥甄|hebe tien/i },
  { region: "tw", id: "yoga", name: "林宥嘉", terms: ["林宥嘉", "Yoga Lin"], match: /林宥嘉|yoga lin/i },
  { region: "tw", id: "accusefive", name: "告五人", terms: ["告五人", "Accusefive"], match: /告五人|accusefive/i },
  { region: "tw", id: "crowdlu", name: "盧廣仲", terms: ["盧廣仲", "Crowd Lu"], match: /盧廣仲|卢广仲|crowd lu/i },
  { region: "tw", id: "lala", name: "徐佳瑩", terms: ["徐佳瑩", "LaLa Hsu"], match: /徐佳瑩|徐佳莹|lala hsu/i },
  { region: "tw", id: "rainie", name: "楊丞琳", terms: ["楊丞琳", "Rainie Yang"], match: /楊丞琳|杨丞琳|rainie yang/i },
  {
    region: "tw",
    id: "hsiao",
    name: "蕭煌奇",
    terms: ["蕭煌奇"],
    match: /蕭煌奇|萧煌奇|ricky hsiao/i,
    colors: { accent: "#3cc6c0", accent2: "#8fe3a8", onAccent: "#04201e" },
  },

  // ---------- 台語 ----------
  { region: "twh", id: "jody", name: "江蕙", terms: ["江蕙", "Jody Chiang"], match: /江蕙|jody chiang/i },
  { region: "twh", id: "wubai", name: "伍佰", terms: ["伍佰", "Wu Bai"], match: /伍佰|wu bai/i },
  { region: "twh", id: "eggplantegg", name: "茄子蛋", terms: ["茄子蛋", "EggPlantEgg"], match: /茄子蛋|eggplantegg/i },
  { region: "twh", id: "jeannie", name: "謝金燕", terms: ["謝金燕", "Jeannie Hsieh"], match: /謝金燕|谢金燕|jeannie hsieh/i },
  { region: "twh", id: "chenlei", name: "陳雷", terms: ["陳雷"], match: /陳雷|陈雷/ },

  // ---------- 日本 ----------
  {
    region: "jp",
    id: "yoasobi",
    name: "YOASOBI",
    icon: "🌙",
    tagline: "把小說變成音樂的兩人組，你認得幾首？",
    terms: ["yoasobi"],
    match: /yoasobi/i,
    // E-SIDE 系列是英文版，歌名不同但旋律一樣，排除以免選項重複
    excludeCollection: /e-side/i,
    colors: { accent: "#6f95ff", accent2: "#ff7ac8", onAccent: "#ffffff" },
    ranks: ["Ayase 和 ikura 本人？🌙", "資深 YOASOBI 迷 📖", "剛讀完第一本 THE BOOK 📘", "先去把《THE BOOK》聽完再來 📀"],
  },
  { region: "jp", id: "yonezu", name: "米津玄師", terms: ["米津玄師", "Kenshi Yonezu"], match: /米津玄師|米津玄师|kenshi yonezu/i },
  { region: "jp", id: "mga", name: "Mrs. GREEN APPLE", short: "Mrs. GREEN APPLE", terms: ["Mrs. GREEN APPLE"], match: /mrs\.? ?green apple/i },
  { region: "jp", id: "higedan", name: "Official髭男dism", short: "髭男", terms: ["Official髭男dism", "Official HIGE DANdism"], match: /official髭男dism|official hige dandism/i },
  { region: "jp", id: "kinggnu", name: "King Gnu", terms: ["King Gnu"], match: /king gnu/i },
  { region: "jp", id: "ado", name: "Ado", terms: ["Ado"], match: /^ado(\s*[,&×x、]|$)/i },
  { region: "jp", id: "aimyon", name: "あいみょん", terms: ["あいみょん", "Aimyon"], match: /あいみょん|aimyon/i },
  { region: "jp", id: "backnumber", name: "back number", terms: ["back number"], match: /back number/i },
  { region: "jp", id: "utada", name: "宇多田ヒカル", short: "宇多田", terms: ["宇多田ヒカル", "Hikaru Utada"], match: /宇多田ヒカル|hikaru utada|^utada$/i },
  { region: "jp", id: "vaundy", name: "Vaundy", terms: ["Vaundy"], match: /vaundy/i },
  // 區分大小寫，避免和泰國的 LISA 混在一起
  { region: "jp", id: "lisa-jp", name: "LiSA", terms: ["LiSA"], match: /^LiSA(\s*[,&×x、]|$)/ },

  // ---------- 歐美 ----------
  {
    region: "west",
    id: "gaga",
    name: "Lady Gaga",
    short: "Gaga",
    icon: "⚡",
    tagline: "你是真正的 Little Monster 嗎？",
    terms: ["lady gaga"],
    match: /lady gaga/i,
    // 《捍衛戰士：獨行俠》原聲帶大多是她和 Hans Zimmer 等人掛名的配樂，太難猜
    excludeCollection: /top gun/i,
    // 《Chromatica》的三段管弦樂間奏很好玩，雖然很短也保留
    allowShort: /^chromatica i+$/i,
    colors: { accent: "#ff2d95", accent2: "#b46bff", onAccent: "#ffffff" },
    ranks: ["Mother Monster 本人？👑", "資深 Little Monster 🐾", "還在練舞的 Monster 💃", "先去把《The Fame》聽完再來 📀"],
  },
  {
    region: "west",
    id: "mj",
    name: "Michael Jackson",
    short: "MJ",
    icon: "🧤",
    tagline: "你跟得上 King of Pop 的舞步嗎？",
    terms: ["michael jackson"],
    match: /michael jackson/i,
    colors: { accent: "#f2c14e", accent2: "#fff1c9", onAccent: "#1a1206" },
    ranks: ["King of Pop 本人？👑", "月球漫步大師 🕺", "還在練 moonwalk 的新手 🧦", "先去把《Thriller》聽完再來 📀"],
  },
  {
    region: "west",
    id: "bruno",
    name: "Bruno Mars",
    short: "Bruno",
    icon: "🎩",
    tagline: "你是真正的 Hooligan 嗎？",
    terms: ["bruno mars"],
    match: /bruno mars/i,
    colors: { accent: "#ff7a3d", accent2: "#ffc857", onAccent: "#1a0c05" },
    ranks: ["Bruno 本人？🎩", "資深 Hooligan 🕶️", "剛戴上 24K 金鍊的新手 🪙", "先去把《Doo-Wops & Hooligans》聽完再來 📀"],
  },
  {
    region: "west",
    id: "ariana",
    name: "Ariana Grande",
    short: "Ariana",
    icon: "🎀",
    tagline: "你是真正的 Arianator 嗎？",
    terms: ["ariana grande"],
    match: /ariana grande/i,
    colors: { accent: "#c9a3ff", accent2: "#ffb3d9", onAccent: "#1b0f2b" },
    ranks: ["Ariana 本人？🎀", "資深 Arianator 💜", "正在綁高馬尾的新手 🎀", "先去把《thank u, next》聽完再來 📀"],
  },
  { region: "west", id: "taylor", name: "Taylor Swift", short: "Taylor", tagline: "你是真正的 Swiftie 嗎？", terms: ["Taylor Swift"], match: /taylor swift/i },
  { region: "west", id: "edsheeran", name: "Ed Sheeran", short: "Ed Sheeran", terms: ["Ed Sheeran"], match: /ed sheeran/i },
  { region: "west", id: "billie", name: "Billie Eilish", short: "Billie", terms: ["Billie Eilish"], match: /billie eilish/i },
  { region: "west", id: "weeknd", name: "The Weeknd", terms: ["The Weeknd"], match: /the weeknd/i },
  { region: "west", id: "adele", name: "Adele", terms: ["Adele"], match: /^adele(\s*[,&]|$)/i },
  { region: "west", id: "dualipa", name: "Dua Lipa", terms: ["Dua Lipa"], match: /dua lipa/i },
  { region: "west", id: "coldplay", name: "Coldplay", terms: ["Coldplay"], match: /coldplay/i },
  { region: "west", id: "beyonce", name: "Beyoncé", terms: ["Beyonce"], match: /beyonc[eé]/i },
  { region: "west", id: "bieber", name: "Justin Bieber", short: "Bieber", terms: ["Justin Bieber"], match: /justin bieber/i },
  { region: "west", id: "olivia", name: "Olivia Rodrigo", short: "Olivia", terms: ["Olivia Rodrigo"], match: /olivia rodrigo/i },

  // ---------- 中國 ----------
  { region: "cn", id: "faye", name: "王菲", terms: ["王菲", "Faye Wong"], match: /王菲|faye wong/i },
  { region: "cn", id: "naying", name: "那英", terms: ["那英", "Na Ying"], match: /那英|na ying/i },
  { region: "cn", id: "zhoushen", name: "周深", terms: ["周深", "Zhou Shen"], match: /周深|zhou shen|charlie zhou/i },
  { region: "cn", id: "maobuyi", name: "毛不易", terms: ["毛不易", "Mao Buyi"], match: /毛不易|mao buyi/i },
  { region: "cn", id: "ronghao", name: "李榮浩", terms: ["李榮浩", "李荣浩", "Ronghao Li"], match: /李榮浩|李荣浩|ronghao li|li ronghao/i },
  { region: "cn", id: "huachenyu", name: "華晨宇", terms: ["華晨宇", "华晨宇", "Hua Chenyu"], match: /華晨宇|华晨宇|hua chenyu/i },
  { region: "cn", id: "janezhang", name: "張靚穎", terms: ["張靚穎", "张靓颖", "Jane Zhang"], match: /張靚穎|张靓颖|jane zhang/i },
  { region: "cn", id: "joker", name: "薛之謙", terms: ["薛之謙", "薛之谦", "Joker Xue"], match: /薛之謙|薛之谦|joker xue/i },
  { region: "cn", id: "lijian", name: "李健", terms: ["李健", "Li Jian"], match: /^李健($|\s*[,&])|li jian/i },
  { region: "cn", id: "pushu", name: "朴樹", terms: ["朴樹", "朴树", "Pu Shu"], match: /朴樹|朴树|樸樹|pu shu/i },

  // ---------- 印度 ----------
  { region: "in", id: "arijit", name: "Arijit Singh", short: "Arijit", terms: ["Arijit Singh"], match: /arijit singh/i },
  { region: "in", id: "rahman", name: "A.R. Rahman", terms: ["A.R. Rahman"], match: /a\.?\s?r\.?\s?rahman/i },
  { region: "in", id: "shreya", name: "Shreya Ghoshal", short: "Shreya", terms: ["Shreya Ghoshal"], match: /shreya ghoshal/i },

  // ---------- 泰國 ----------
  { region: "th", id: "bodyslam", name: "Bodyslam", terms: ["Bodyslam", "บอดี้สแลม"], match: /bodyslam|บอดี้สแลม/i },
  { region: "th", id: "palmy", name: "Palmy", terms: ["Palmy", "ปาล์มมี่"], match: /palmy|ปาล์มมี่/i },
  { region: "th", id: "phum", name: "Phum Viphurit", short: "Phum", terms: ["Phum Viphurit"], match: /phum viphurit/i },
];


// ---------- 全球百大裡原本沒有的歌手 ----------
// 名字很短或很常見的，用 ^…$ 比對整個歌手名稱，避免抓到同名的其他人
const more = (region, id, name, terms, match, extra = {}) => ({ region, id, name, terms, match, ...extra });
window.ARTISTS.push(
  more("west", "drake", "Drake", ["Drake"], /^drake(\s*[,&]|$)/i),
  more("west", "eminem", "Eminem", ["Eminem"], /eminem/i),
  more("west", "rihanna", "Rihanna", ["Rihanna"], /rihanna/i),
  more("west", "postmalone", "Post Malone", ["Post Malone"], /post malone/i),
  more("west", "kendrick", "Kendrick Lamar", ["Kendrick Lamar"], /kendrick lamar/i, { short: "Kendrick" }),
  more("west", "sza", "SZA", ["SZA"], /^sza(\s*[,&]|$)/i),
  more("west", "dojacat", "Doja Cat", ["Doja Cat"], /doja cat/i),
  more("west", "harrystyles", "Harry Styles", ["Harry Styles"], /harry styles/i, { short: "Harry" }),
  more("west", "imaginedragons", "Imagine Dragons", ["Imagine Dragons"], /imagine dragons/i),
  more("west", "maroon5", "Maroon 5", ["Maroon 5"], /maroon 5/i),
  more("west", "katyperry", "Katy Perry", ["Katy Perry"], /katy perry/i, { short: "Katy" }),
  more("west", "sabrina", "Sabrina Carpenter", ["Sabrina Carpenter"], /sabrina carpenter/i, { short: "Sabrina" }),
  more("west", "lanadelrey", "Lana Del Rey", ["Lana Del Rey"], /lana del rey/i, { short: "Lana" }),
  more("west", "arcticmonkeys", "Arctic Monkeys", ["Arctic Monkeys"], /arctic monkeys/i),
  more("west", "linkinpark", "Linkin Park", ["Linkin Park"], /linkin park/i),
  more("west", "queen", "Queen", ["Queen"], /^queen(\s*[,&]|$)/i),
  more("west", "beatles", "The Beatles", ["The Beatles"], /^the beatles$/i),
  more("west", "eltonjohn", "Elton John", ["Elton John"], /elton john/i),
  more("west", "madonna", "Madonna", ["Madonna"], /^madonna(\s*[,&]|$)/i),
  more("west", "whitney", "Whitney Houston", ["Whitney Houston"], /whitney houston/i, { short: "Whitney" }),
  more("west", "mariah", "Mariah Carey", ["Mariah Carey"], /mariah carey/i, { short: "Mariah" }),
  more("west", "elvis", "Elvis Presley", ["Elvis Presley"], /elvis presley/i, { short: "Elvis" }),
  more("west", "abba", "ABBA", ["ABBA"], /^abba$/i),
  more("west", "bobmarley", "Bob Marley", ["Bob Marley"], /bob marley/i),
  more("west", "nirvana", "Nirvana", ["Nirvana"], /^nirvana$/i),
  more("west", "metallica", "Metallica", ["Metallica"], /^metallica(\s*[,&]|$)/i),
  more("west", "acdc", "AC/DC", ["AC/DC"], /^ac\/dc$/i),
  more("west", "gnr", "Guns N' Roses", ["Guns N' Roses"], /guns n['’]? roses/i),
  more("west", "rhcp", "Red Hot Chili Peppers", ["Red Hot Chili Peppers"], /red hot chili peppers/i, { short: "嗆辣紅椒" }),
  more("west", "oasis", "Oasis", ["Oasis"], /^oasis$/i),
  more("west", "radiohead", "Radiohead", ["Radiohead"], /^radiohead$/i),
  more("west", "u2", "U2", ["U2"], /^u2(\s*[,&]|$)/i),
  more("west", "bonjovi", "Bon Jovi", ["Bon Jovi"], /^bon jovi$/i),
  more("west", "pinkfloyd", "Pink Floyd", ["Pink Floyd"], /^pink floyd$/i),
  more("west", "ledzeppelin", "Led Zeppelin", ["Led Zeppelin"], /^led zeppelin$/i),
  more("west", "rollingstones", "The Rolling Stones", ["The Rolling Stones"], /rolling stones/i, { short: "滾石" }),
  more("west", "fleetwoodmac", "Fleetwood Mac", ["Fleetwood Mac"], /^fleetwood mac$/i),
  more("west", "eagles", "Eagles", ["Eagles"], /^eagles$/i),
  more("west", "prince", "Prince", ["Prince"], /^prince(\s*[,&]|$)/i),
  more("west", "steviewonder", "Stevie Wonder", ["Stevie Wonder"], /stevie wonder/i, { short: "Stevie" }),
  more("west", "bowie", "David Bowie", ["David Bowie"], /david bowie/i, { short: "Bowie" }),
  more("west", "britney", "Britney Spears", ["Britney Spears"], /britney spears/i, { short: "Britney" }),
  more("west", "timberlake", "Justin Timberlake", ["Justin Timberlake"], /justin timberlake/i, { short: "JT" }),
  more("west", "usher", "Usher", ["Usher"], /^usher(\s*[,&]|$)/i),
  more("west", "aliciakeys", "Alicia Keys", ["Alicia Keys"], /alicia keys/i, { short: "Alicia" }),
  more("west", "sia", "Sia", ["Sia"], /^sia(\s*[,&]|$)/i),
  more("west", "shawnmendes", "Shawn Mendes", ["Shawn Mendes"], /shawn mendes/i, { short: "Shawn" }),
  more("west", "charlieputh", "Charlie Puth", ["Charlie Puth"], /charlie puth/i, { short: "Charlie" }),
  more("west", "samsmith", "Sam Smith", ["Sam Smith"], /^sam smith(\s*[,&]|$)/i),
  more("west", "capaldi", "Lewis Capaldi", ["Lewis Capaldi"], /lewis capaldi/i, { short: "Capaldi" }),
  more("west", "onerepublic", "OneRepublic", ["OneRepublic"], /onerepublic/i),
  more("west", "calvinharris", "Calvin Harris", ["Calvin Harris"], /calvin harris/i),
  more("west", "guetta", "David Guetta", ["David Guetta"], /david guetta/i, { short: "Guetta" }),
  more("west", "avicii", "Avicii", ["Avicii"], /avicii/i),
  more("west", "daftpunk", "Daft Punk", ["Daft Punk"], /daft punk/i),
  more("west", "marshmello", "Marshmello", ["Marshmello"], /marshmello/i),
  more("west", "chainsmokers", "The Chainsmokers", ["The Chainsmokers"], /chainsmokers/i),
  more("west", "travisscott", "Travis Scott", ["Travis Scott"], /travis scott/i),
  more("west", "future", "Future", ["Future"], /^future(\s*[,&]|$)/i),
  more("west", "nickiminaj", "Nicki Minaj", ["Nicki Minaj"], /nicki minaj/i, { short: "Nicki" }),
  more("west", "cardib", "Cardi B", ["Cardi B"], /^cardi b(\s*[,&]|$)/i),
  more("west", "jayz", "JAY-Z", ["JAY-Z"], /^jay[- ]?z(\s*[,&]|$)/i),
  more("west", "snoop", "Snoop Dogg", ["Snoop Dogg"], /snoop dogg/i, { short: "Snoop" }),
  more("west", "fiftycent", "50 Cent", ["50 Cent"], /^50 cent(\s*[,&]|$)/i),
  more("west", "selena", "Selena Gomez", ["Selena Gomez"], /selena gomez/i, { short: "Selena" }),
  more("west", "miley", "Miley Cyrus", ["Miley Cyrus"], /miley cyrus/i, { short: "Miley" }),
  more("west", "pink", "P!nk", ["P!nk", "Pink"], /^p!nk(\s*[,&]|$)/i),
  more("west", "greenday", "Green Day", ["Green Day"], /^green day$/i),
  more("west", "twentyonepilots", "Twenty One Pilots", ["Twenty One Pilots"], /twenty one pilots/i, { short: "21 Pilots" }),
  more("west", "frankocean", "Frank Ocean", ["Frank Ocean"], /frank ocean/i),
  more("west", "celine", "Céline Dion", ["Celine Dion"], /c[eé]line dion/i, { short: "Céline" }),
  more("west", "morganwallen", "Morgan Wallen", ["Morgan Wallen"], /morgan wallen/i),

  more("kr", "bts", "BTS", ["BTS"], /^bts(\s*[,&]|$)/i, { tagline: "你是真正的 ARMY 嗎？" }),
  more("kr", "blackpink", "BLACKPINK", ["BLACKPINK"], /^blackpink(\s*[,&]|$)/i, { tagline: "你是真正的 BLINK 嗎？" }),
  more("kr", "twice", "TWICE", ["TWICE"], /^twice(\s*[,&]|$)/i),
  more("kr", "newjeans", "NewJeans", ["NewJeans"], /^newjeans(\s*[,&]|$)/i),
  more("kr", "straykids", "Stray Kids", ["Stray Kids"], /^stray kids(\s*[,&]|$)/i),
  more("kr", "psy", "PSY", ["PSY"], /^psy(\s*[,&]|$)/i),
  more("kr", "iu", "IU", ["IU"], /^iu(\s*[,&(]|$)/i),

  more("latin", "badbunny", "Bad Bunny", ["Bad Bunny"], /bad bunny/i),
  more("latin", "shakira", "Shakira", ["Shakira"], /shakira/i),
  more("latin", "jbalvin", "J Balvin", ["J Balvin"], /j\.? ?balvin/i),
  more("latin", "karolg", "KAROL G", ["KAROL G"], /karol g\b/i),
  more("latin", "daddyyankee", "Daddy Yankee", ["Daddy Yankee"], /daddy yankee/i),
  more("latin", "ozuna", "Ozuna", ["Ozuna"], /^ozuna(\s*[,&]|$)/i),
  more("latin", "rosalia", "ROSALÍA", ["Rosalia"], /^rosal[ií]a(\s*[,&]|$)/i),
);

// ---------- 台灣、台語加碼 ----------
// 中文名字都很獨特，比對簡繁體與英文名即可；很短的名字用 ^…$ 避免抓到別人
window.ARTISTS.push(
  more("tw", "cyndi", "王心凌", ["王心凌", "Cyndi Wang"], /王心凌|cyndi wang/i),
  more("tw", "sodagreen", "蘇打綠", ["蘇打綠", "Sodagreen"], /蘇打綠|苏打绿|sodagreen|魚丁糸/i),
  more("tw", "qingfeng", "吳青峰", ["吳青峰", "Qing Feng Wu"], /吳青峰|吴青峰|qing ?feng wu|wu tsing-fong/i),
  more("tw", "weibird", "韋禮安", ["韋禮安", "WeiBird"], /韋禮安|韦礼安|weibird/i),
  more("tw", "cheerchen", "陳綺貞", ["陳綺貞", "Cheer Chen"], /陳綺貞|陈绮贞|cheer chen/i),
  more("tw", "jonathanlee", "李宗盛", ["李宗盛", "Jonathan Lee"], /李宗盛|jonathan lee/i),
  more("tw", "tomchang", "張雨生", ["張雨生"], /張雨生|张雨生/),
  more("tw", "teresateng", "鄧麗君", ["鄧麗君", "Teresa Teng"], /鄧麗君|邓丽君|teresa teng/i),
  more("tw", "feiyuching", "費玉清", ["費玉清", "Fei Yu-Ching"], /費玉清|费玉清|fei yu-?ching/i),
  more("tw", "reneliu", "劉若英", ["劉若英", "Rene Liu"], /劉若英|刘若英|rene liu/i),
  more("tw", "davidtao", "陶喆", ["陶喆", "David Tao"], /陶喆|david tao/i),
  more("tw", "angelachang", "張韶涵", ["張韶涵", "Angela Chang"], /張韶涵|张韶涵|angela chang/i),
  more("tw", "she", "S.H.E", ["S.H.E"], /^s\.?h\.?e(\s*[,&]|$)/i),
  more("tw", "powerstation", "動力火車", ["動力火車", "Power Station"], /動力火車|动力火车|power station/i),
  more("tw", "831", "八三夭", ["八三夭", "831"], /八三夭|^831$/i),
  more("tw", "caodong", "草東沒有派對", ["草東沒有派對", "No Party For Cao Dong"], /草東沒有派對|草东没有派对|no party for cao dong/i, { short: "草東" }),
  more("tw", "sunsetrollercoaster", "落日飛車", ["落日飛車", "Sunset Rollercoaster"], /落日飛車|落日飞车|sunset rollercoaster/i),
  more("tw", "waawei", "魏如萱", ["魏如萱", "Waa Wei"], /魏如萱|waa wei/i),
  more("tw", "9m88", "9m88", ["9m88"], /^9m88(\s*[,&]|$)/i),
  more("tw", "deserts", "張懸／安溥", ["張懸", "安溥", "Deserts Chang"], /張懸|张悬|安溥|deserts chang/i, { short: "張懸" }),
  more("tw", "ericchou", "周興哲", ["周興哲", "Eric Chou"], /周興哲|周兴哲|eric chou/i),
  more("tw", "jamhsiao", "蕭敬騰", ["蕭敬騰", "Jam Hsiao"], /蕭敬騰|萧敬腾|jam hsiao/i),
  more("tw", "harlemyu", "庾澄慶", ["庾澄慶", "Harlem Yu"], /庾澄慶|庾澄庆|harlem yu/i),
  more("tw", "wakin", "周華健", ["周華健", "Wakin Chau"], /周華健|周华健|wakin chau|emil chau/i),
  more("tw", "richiejen", "任賢齊", ["任賢齊", "Richie Jen"], /任賢齊|任贤齐|richie (jen|ren)/i),
  more("tw", "ayue", "張震嶽", ["張震嶽", "A-Yue"], /張震嶽|张震岳|a-?yue|ayal komod/i),
  more("tw", "mj116", "頑童MJ116", ["頑童MJ116", "MJ116"], /頑童|顽童|mj116/i),
  more("tw", "cosmospeople", "宇宙人", ["宇宙人", "Cosmos People"], /宇宙人|cosmos people/i),
  more("tw", "eveai", "艾怡良", ["艾怡良", "Eve Ai"], /艾怡良|eve ai/i),
  more("tw", "naiwen", "楊乃文", ["楊乃文", "Faith Yang"], /楊乃文|杨乃文|faith yang/i),
  more("tw", "chyichin", "齊秦", ["齊秦", "Chyi Chin"], /齊秦|齐秦|chyi chin/i),
  more("tw", "maggiechiang", "江美琪", ["江美琪", "Maggie Chiang"], /江美琪|maggie chiang/i),
  more("tw", "wilberpan", "潘瑋柏", ["潘瑋柏", "Wilber Pan"], /潘瑋柏|潘玮柏|wilber pan/i),

  more("twh", "yehchitien", "葉啟田", ["葉啟田"], /葉啟田|叶启田/),
  more("twh", "hungjunghung", "洪榮宏", ["洪榮宏"], /洪榮宏|洪荣宏/),
  more("twh", "huangyiling", "黃乙玲", ["黃乙玲"], /黃乙玲|黄乙玲/),
  more("twh", "lungchienyu", "龍千玉", ["龍千玉"], /龍千玉|龙千玉/),
  more("twh", "tsaichiufeng", "蔡秋鳳", ["蔡秋鳳"], /蔡秋鳳|蔡秋凤/),
  more("twh", "chanyawen", "詹雅雯", ["詹雅雯"], /詹雅雯/),
  more("twh", "huangfei", "黃妃", ["黃妃"], /^(黃妃|黄妃)($|\s*[,&])/),
  more("twh", "tsenghsinmei", "曾心梅", ["曾心梅"], /曾心梅/),
  more("twh", "chenyalan", "陳亞蘭", ["陳亞蘭"], /陳亞蘭|陈亚兰/),
  more("twh", "wangshihhsien", "王識賢", ["王識賢"], /王識賢|王识贤/),
  more("twh", "wengliyu", "翁立友", ["翁立友"], /翁立友/),
  more("twh", "chiangchihfeng", "江志豐", ["江志豐"], /江志豐|江志丰/),
  more("twh", "huangshanliang", "荒山亮", ["荒山亮"], /荒山亮/),
  more("twh", "chenyingchieh", "陳盈潔", ["陳盈潔"], /陳盈潔|陈盈洁/),
  more("twh", "chengchinyi", "鄭進一", ["鄭進一"], /鄭進一|郑进一/),
  more("twh", "loshihfeng", "羅時豐", ["羅時豐"], /羅時豐|罗时丰/),
  more("twh", "tsaihsiaohu", "蔡小虎", ["蔡小虎"], /蔡小虎/),
  more("twh", "wushenmei", "吳申梅", ["吳申梅"], /吳申梅|吴申梅/),
  more("twh", "changhsiuching", "張秀卿", ["張秀卿"], /張秀卿|张秀卿/),
  more("twh", "hungyifeng", "洪一峰", ["洪一峰"], /洪一峰/),
  more("twh", "wenhsia", "文夏", ["文夏"], /^文夏($|\s*[,&])/),
  more("twh", "chenmingchang", "陳明章", ["陳明章"], /陳明章|陈明章/),
  more("twh", "limgiong", "林強", ["林強", "Lim Giong"], /^(林強|林强)($|\s*[,&])|lim giong/i),
  more("twh", "fireex", "滅火器", ["滅火器", "Fire EX."], /滅火器|灭火器|fire ex\.?/i),
  more("twh", "amazingshow", "美秀集團", ["美秀集團", "Amazing Show"], /美秀集團|美秀集团|amazing show/i),
  more("twh", "chthonic", "閃靈", ["閃靈", "Chthonic"], /閃靈|闪灵|chthonic/i),
  more("twh", "sorryyouth", "拍謝少年", ["拍謝少年", "Sorry Youth"], /拍謝少年|拍谢少年|sorry youth/i),
  more("twh", "chairman", "董事長樂團", ["董事長樂團", "The Chairman"], /董事長樂團|董事长乐团|the chairman/i, { short: "董事長" }),
);

// 全球百大：串流與歷史銷量都有考量，兼顧經典與現役，依名次排列
window.TOP100 = [
  "taylor", "drake", "badbunny", "weeknd", "edsheeran", "ariana", "bieber", "eminem", "bts", "billie",
  "rihanna", "postmalone", "coldplay", "bruno", "dualipa", "gaga", "beyonce", "adele", "mj", "kendrick",
  "sza", "dojacat", "harrystyles", "olivia", "imaginedragons", "maroon5", "katyperry", "shakira", "jbalvin", "karolg",
  "sabrina", "lanadelrey", "arcticmonkeys", "linkinpark", "queen", "beatles", "eltonjohn", "madonna", "whitney", "mariah",
  "elvis", "abba", "bobmarley", "nirvana", "metallica", "acdc", "gnr", "rhcp", "oasis", "radiohead",
  "u2", "bonjovi", "pinkfloyd", "ledzeppelin", "rollingstones", "fleetwoodmac", "eagles", "prince", "steviewonder", "bowie",
  "britney", "timberlake", "usher", "aliciakeys", "sia", "shawnmendes", "charlieputh", "samsmith", "capaldi", "onerepublic",
  "calvinharris", "guetta", "avicii", "daftpunk", "marshmello", "chainsmokers", "travisscott", "future", "nickiminaj", "cardib",
  "jayz", "snoop", "fiftycent", "daddyyankee", "ozuna", "rosalia", "selena", "miley", "pink", "greenday",
  "twentyonepilots", "blackpink", "twice", "newjeans", "straykids", "psy", "frankocean", "celine", "morganwallen", "iu",
];

// 搜尋用的中文俗稱
const ALIASES = {
  gaga: "女神卡卡 卡卡", mj: "麥可傑克森 麥可 流行天王", bruno: "火星人布魯諾 火星人", ariana: "亞莉安娜 A妹",
  taylor: "泰勒絲 霉霉", edsheeran: "紅髮艾德", billie: "怪奇比莉", weeknd: "威肯 盛宴", adele: "愛黛兒",
  dualipa: "杜娃黎波", coldplay: "酷玩樂團", beyonce: "碧昂絲", bieber: "小賈斯汀", olivia: "奧莉維亞",
  drake: "德瑞克 公鴨", eminem: "阿姆", rihanna: "蕾哈娜", postmalone: "波茲瑪龍 小馬", kendrick: "肯卓克",
  dojacat: "朵佳貓", harrystyles: "哈利 哈利史泰爾斯", imaginedragons: "謎幻樂團", maroon5: "魔力紅",
  katyperry: "凱蒂佩芮 水果姐", sabrina: "莎賓娜", lanadelrey: "拉娜德芮", arcticmonkeys: "北極潑猴",
  linkinpark: "聯合公園", queen: "皇后合唱團", beatles: "披頭四", eltonjohn: "艾爾頓強", madonna: "瑪丹娜",
  whitney: "惠妮休斯頓", mariah: "瑪麗亞凱莉 牛姐", elvis: "貓王", abba: "阿巴合唱團", bobmarley: "巴布馬利",
  nirvana: "超脫樂團", metallica: "金屬製品", gnr: "槍與玫瑰", rhcp: "嗆辣紅椒", oasis: "綠洲合唱團",
  radiohead: "電台司令", bonjovi: "邦喬飛", pinkfloyd: "平克佛洛伊德", ledzeppelin: "齊柏林飛船",
  rollingstones: "滾石樂團", fleetwoodmac: "佛利伍麥克", eagles: "老鷹合唱團", prince: "王子",
  steviewonder: "史提夫汪達", bowie: "大衛鮑伊", britney: "小甜甜布蘭妮 布蘭妮", timberlake: "賈斯汀",
  aliciakeys: "艾莉西亞凱斯", shawnmendes: "尚恩曼德斯", charlieputh: "查理普斯", samsmith: "山姆史密斯",
  calvinharris: "凱文哈里斯", avicii: "艾維奇", daftpunk: "傻瓜龐克", marshmello: "棉花糖",
  chainsmokers: "老菸槍", nickiminaj: "妮琪米娜", selena: "席琳娜", miley: "麥莉", pink: "紅粉佳人",
  greenday: "年輕歲月", celine: "席琳狄翁", bts: "防彈少年團 防彈", blackpink: "粉墨",
  psy: "江南大叔", iu: "李知恩", badbunny: "壞痞兔", shakira: "夏奇拉",
  jay: "周董", amei: "阿妹", jolin: "Jolin", hebe: "Hebe", mayday: "阿信",
  cyndi: "甜心教主 心凌", sodagreen: "魚丁糸 青峰", teresateng: "小鄧", feiyuching: "小哥", jonathanlee: "老李",
  wakin: "華健", richiejen: "小齊", ayue: "阿嶽", harlemyu: "哈林", she: "Selina Hebe Ella", jody: "二姊",
  wubai: "伍佰老師 China Blue", jeannie: "姊姊", caodong: "草東", amazingshow: "美秀", deserts: "安溥",
};

// 名字結尾是英文或數字才補空格：「Gaga 猜歌王」、「周杰倫猜歌王」
window.withName = (name, rest) => (/[A-Za-z0-9.]$/.test(name) ? `${name} ${rest}` : `${name}${rest}`);

// 用地區預設值補齊每位歌手沒寫到的欄位
for (const artist of window.ARTISTS) {
  const region = window.REGIONS.find((r) => r.id === artist.region);
  const short = artist.short || artist.name;
  Object.assign(artist, {
    short,
    icon: artist.icon || region.icon,
    countries: artist.countries || region.countries,
    colors: artist.colors || region.colors,
    tagline: artist.tagline || window.withName(artist.name, "的歌，你認得幾首？"),
    top: window.TOP100.indexOf(artist.id) + 1 || null,
    // 搜尋用：名稱、搜尋關鍵字與中文俗稱全部串起來
    searchText: [artist.name, artist.short, ...(artist.terms || []), ALIASES[artist.id] || ""].join(" ").toLowerCase(),
    ranks: artist.ranks || [window.withName(short, "本人？👑"), "資深歌迷 🎧", "有在認真聽的路人 🙂", "先去多聽幾首再來 📀"],
  });
}

// 線索題庫的精簡寫法：
// t 歌名、a 專輯、y 專輯年份、f 冷知識、e emoji、w 自訂第二條線索（非專輯單曲或客串時用）、deep 非主打的冷門歌
window.CLUES = {};
window.defineClues = function (id, rows) {
  window.CLUES[id] = rows.map((r) => ({
    title: r.t,
    album: r.a || "",
    year: r.y,
    deep: Boolean(r.deep),
    clues: [r.f, r.w || `收錄於《${r.a}》（${r.y}）。`, r.e],
  }));
};
